apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant
spec:
  selector:
    matchLabels:
      app: restaurant
  replicas: 2
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
      - name: restaurant
        image: estebanlamanna/test_netcore_redis_restaurant:v4
        ports:
        - containerPort: 80
        env: 
        - name: Test__Child1
          valueFrom: 
            configMapKeyRef:
                name: restaurant-config
                key: Test__Child1
        - name: ConnectionStrings__sqlServer
          valueFrom: 
            configMapKeyRef:
                name: restaurant-config
                key: ConnectionStrings__sqlServer