# apiVersion: apps/v1
# kind: Deployment
# metadata:
  # name: sqlserver
# spec:
  # replicas: 1
  # selector:
     # matchLabels:
       # name: sqlserver
  # template:
    # metadata:
      # labels:
        # name: sqlserver
    # spec:
      # containers:
      # - name: sqlserver1
        # image: mcr.microsoft.com/mssql/server
        # ports:
        # - containerPort: 1433
        # env:
        # - name: SA_PASSWORD
          # value: "Figueroa36004788!"
        # - name: ACCEPT_EULA
          # value: "Y"